### PR TITLE
feat: Add devcontainer support for alternative development options

### PR DESCRIPTION
**Pull request by ChrisLGardner**
## ✅ Changes

- feat: add devcontainer support for alternative development options

## 🌄 Context

Devcontainer support will allow more contributions without a need for them to install specific versions of node/npm locally.

### CODE REVIEW

**Comment by ChrisLGardner** [comment]
I'll fix the massive changes to the readme so it's a bit more sensible, just wanted to get the PR in initially.

**Comment by RPDeshaies** [comment]
Oh cool, I love this!

**Comment by ChrisLGardner** [comment]
Not sure if there's anything I can do about the preview deploy failing. There shouldn't be anything in the change that'd impact the normal deploy process.

**Comment by RPDeshaies** [comment]
yeah no don't worry about that!

**Review by RPDeshaies — APPROVED** [review]

**Comment by RPDeshaies** [comment]
I'll merge this in v6 which should be live on master in a week or two

**Pull request merged**
